// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appspot.gardemallorie.domain;

import com.appspot.gardemallorie.domain.GardeIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect GardeIntegrationTest_Roo_Configurable {
    
    declare @type: GardeIntegrationTest: @Configurable;
    
}
