// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.appspot.gardemallorie.domain;


privileged aspect Location_Roo_JavaBean {
    
    public String Location.getName() {
        return this.name;
    }
    
    public void Location.setName(String name) {
        this.name = name;
    }
    
}
